[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific redirects for your routes
[[redirects]]
  from = "/blog"
  to = "/blog/index.html"
  status = 200

[[redirects]]
  from = "/sobre"
  to = "/sobre/index.html"
  status = 200

[[redirects]]
  from = "/contacto"
  to = "/contacto/index.html"
  status = 200 